export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const SEND_QUESTION = "SEND_QUESTION";
export const SET_ISLOADING = "SET_ISLOADING";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
